repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/zmoon/findent-pre-commit
    rev: "65627b8"
    hooks:
      # NOTE: doesn't work on Windows currently
      - id: findent-pypi
        args: ['-i3']
