foreach(opt IN LISTS _catchem_compiler_options)
  add_compile_options("$<$<COMPILE_LANGUAGE:Fortran>:${opt}>")
endforeach()

add_subdirectory(seasalt)
add_subdirectory(dust)
#add_subdirectory(plumerise)
add_subdirectory(drydep)
add_subdirectory(wetdep)
add_subdirectory(settling)
add_subdirectory(so4chem)
add_subdirectory(carbchem)

if(CATCHEM_BUILD_MUSICA)
  add_subdirectory(photolysis)
  add_subdirectory(gaschem)
endif()
