name: CI (Intel)

on:
  workflow_call:

jobs:
  build-and-test-intel:
    name: Build and test (Intel)
    runs-on: ubuntu-latest
    container: ghcr.io/noaa-emc/ci-common-build-cache/ufs-weather-model-ubuntu-24.04-oneapi-2025.3-intel-oneapi-mpi-2021.17

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install Intel compilers & MPI
        uses: NOAA-EMC/ci-install-intel-toolkit@develop
        with:
          install-mpi: true
          mpi-wrapper-setup: oneapi
          env-update: true

      - name: Configure
        run: |
          . /entrypoint.sh
          mkdir build && cd build
          cmake .. \
            -DCATCHEM_BUILD_TESTING=ON \
            -DCATCHEM_BUILD_NUOPC=ON \
            -DCATCHEM_BUILD_MUSICA=ON \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          . /entrypoint.sh
          cmake --build build -j2

      - name: Test
        run: |
          . /entrypoint.sh
          ctest --test-dir build --output-on-failure
