name: Docker Cleanup

on:
  workflow_call:
    inputs:
      short_sha:
        description: 'The short SHA of the commit'
        required: true
        type: string
      base_project_name:
        description: 'The base project name'
        required: true
        type: string

jobs:
  delete-tags:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Delete temporary Docker Hub tags
        run: |
          # 1. Get JWT Token
          LOGIN_RESPONSE=$(curl -v -s -H "Content-Type: application/json" \
            -X POST \
            -d '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' \
            https://hub.docker.com/v2/users/login/)

          TOKEN=$(echo "$LOGIN_RESPONSE" | jq -r .token)

          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
            echo "Failed to authenticate with Docker Hub"
            exit 1
          fi

          # List of repositories to clean up
          REPOS=("${{ inputs.base_project_name }}")

          for REPO in "${REPOS[@]}"; do
            echo "Deleting tag ${{ inputs.short_sha }} from $REPO"
            curl -v -s --fail -X DELETE \
              -H "Authorization: JWT ${TOKEN}" \
              "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/${REPO}/tags/dev-${{ inputs.short_sha }}/"
          done
