name: main

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  docker-verify:
    uses: ./.github/workflows/docker-verify.yml
    with:
      target: ${{ github.base_ref || github.ref_name }}

  docker-setup:
    uses: ./.github/workflows/docker-setup.yml
    with:
      docker_org: ${{ vars.DOCKER_ORG }}
      target: ${{ github.base_ref || github.ref_name }}

  lint:
    uses: ./.github/workflows/lint.yml

  ci-gnu:
    uses: ./.github/workflows/build-and-test-gcc.yml

  ci-intel:
    uses: ./.github/workflows/build-and-test-intel.yml

  docker-develop:
    needs: [docker-setup]
    uses: ./.github/workflows/docker.yml
    with:
      project_name: catchem-dev
      base_image: ${{ needs.docker-setup.outputs.base_image }}
    secrets: inherit

  release-preview:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    uses: ./.github/workflows/semantic-release.yml
    with:
      dry_run: true
      target_branch: ${{ github.base_ref || github.ref_name }}
      pr_title: ${{ github.event.pull_request.title || '' }}
    secrets: inherit

  release:
    needs: [lint, ci-gnu, ci-intel, docker-develop, docker-verify]
    if: github.event_name == 'push'
    uses: ./.github/workflows/semantic-release.yml
    with:
      dry_run: false
      target_branch: ${{ github.ref_name }}
    secrets: inherit

  docker-release:
    needs: [docker-setup, release, docker-develop]
    if: needs.release.outputs.new_release_published == 'true'
    uses: ./.github/workflows/docker-release.yml
    with:
      release_version: ${{ needs.release.outputs.new_release_version }}
      base_image: ${{ needs.release.outputs.is_prerelease == 'true' && needs.docker-setup.outputs.base_image_dev || needs.docker-setup.outputs.base_image_prod }}
      project_name: ${{ needs.release.outputs.is_prerelease == 'true' && needs.docker-setup.outputs.project_name_dev || needs.docker-setup.outputs.project_name }}
    secrets: inherit

  docs:
    needs: [lint, ci-gnu, ci-intel, release, docker-develop]
    if: always() && !failure() && !cancelled()
    uses: ./.github/workflows/docs.yml
