name: CI (spack-stack)

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

# Use custom shell with -l so .bash_profile is sourced
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  cache_key: gcc

# The jobs are split into:
# 1. a dependency build step (setup), and
# 2. a catchem build and test step (catchem)
# The setup is run once and the environment is cached,
# so each subsequent build and test of catchem can reuse the cached
# dependencies to save time (and compute).

jobs:
  setup:
    # NOTE: this can take quite a while if the cache misses.
    runs-on: ubuntu-24.04

    steps:
      - name: checkout  # this is to get the ci/spack.yaml file
        uses: actions/checkout@v6
        with:
          path: catchem

      # Cache spack, compiler and dependencies
      - name: cache-env
        id: cache-env
        uses: actions/cache@v5
        with:
          path: |
            spack
            ~/.spack
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('catchem/ci/spack.yaml') }}

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          git clone -c feature.manyFiles=true https://github.com/JCSDA/spack.git --branch spack-stack-1.9.3 --depth 1
          source spack/share/spack/setup-env.sh
          sed "s/\[oneapi, gcc@13.13, apple-clang@14\]/\[gcc@13\]/g" catchem/ci/spack.yaml > spack_ci.yaml
          spack env create catchem-env spack_ci.yaml
          spack env activate catchem-env
          sudo apt-get update && sudo apt-get install -y libgomp1
          spack compiler find
          spack external find
          # Ensure MPI with Fortran and OpenMP-capable toolchain
          spack add mpich@3.4.2 %gcc@13
          spack concretize
          spack install -v --fail-fast --dirty
          spack clean --all

  catchem:
    needs: setup
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          path: catchem
          submodules: recursive

      - name: cache-env
        id: cache-env
        uses: actions/cache@v5
        with:
          path: |
            spack
            ~/.spack
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('catchem/ci/spack.yaml') }}

      - name: build
        run: |
          source spack/share/spack/setup-env.sh
          spack env activate catchem-env
          export CC=mpicc
          export FC=mpif90
          export MPICH_CC=gcc-13
          export MPICH_FC=gfortran-13
          export MPICH_CXX=g++-13
          cd catchem
          mkdir -p build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=../install -DBUILD_NUOPC=ON ..
          make -j2 VERBOSE=1
          make install

      - name: test
        run: |
          source spack/share/spack/setup-env.sh
          spack env activate catchem-env
          cd catchem/build
          ctest --output-on-failure
